// Generated by `npm run build` — edit src/adblock-core.js + src/tampermonkey-header.txt only.

(() => {
  'use strict';

  const PLAYER_CDN_HOST = /^storage\.googleapiscdn\.com$/i;

  /**
   * Pause-ad UI lives inside the player iframe (cross-origin from animevietsub).
   * Parent page cannot touch iframe DOM; runs on storage.googleapiscdn.com (second content_scripts match; excluded from the global match to avoid double inject).
   */
  function runEmbeddedPlayerAdDismiss() {
    const verbose = true;
    const debounceMs = 72;
    const log = (msg, icon = '🎬') => verbose && console.log(`${icon} [AVS-player] ${msg}`);

    const RESUME_CHIP_ID = '__avs_resume_chip';
    let debounceTimer = 0;
    let mo = null;
    let burstUntil = 0;
    let burstTimer = 0;

    function visible(el) {
      if (!el?.isConnected) return false;
      const st = window.getComputedStyle(el);
      if (st.display === 'none' || st.visibility === 'hidden' || Number(st.opacity) === 0) return false;
      const r = el.getBoundingClientRect();
      return r.width > 0 && r.height > 0;
    }

    function norm(s) {
      return (s || '').replace(/\s+/g, ' ').trim();
    }

    function hardHide(el) {
      if (!el || el.nodeType !== Node.ELEMENT_NODE) return;
      if (el.id === RESUME_CHIP_ID) return;
      el.style.setProperty('display', 'none', 'important');
      el.style.setProperty('visibility', 'hidden', 'important');
      el.style.setProperty('pointer-events', 'none', 'important');
      el.style.setProperty('max-height', '0', 'important');
      el.style.setProperty('overflow', 'hidden', 'important');
      el.style.setProperty('opacity', '0', 'important');
    }

    /** “Đóng quảng cáo” = ad trap — never follow click. */
    function blockDeceptiveAdCloseClicks() {
      const trap = /Đóng quảng cáo/i;
      const safe = /Đóng và xem tiếp/i;
      const handler = e => {
        const hit = e.target?.closest?.('a, button, [role="button"], div[onclick], input[type="button"], span[onclick]');
        if (!hit || !visible(hit)) return;
        const label = norm(hit.textContent);
        if (trap.test(label) && !safe.test(label)) {
          e.preventDefault();
          e.stopImmediatePropagation();
          log('Blocked deceptive “Đóng quảng cáo” (redirect)');
        }
      };
      for (const evt of ['pointerdown', 'click', 'auxclick']) {
        document.addEventListener(evt, handler, { capture: true, passive: false });
      }
    }

    /** Banner img + fake row pieces (DOM-local). */
    function hidePauseAdParts() {
      const clickables = document.querySelectorAll(
        'button, a, [role="button"], input[type="button"], [class*="btn"], div[onclick], span[onclick]'
      );
      for (const el of clickables) {
        if (!visible(el)) continue;
        const label = norm(el.textContent);
        if (!/Đóng quảng cáo/i.test(label) || /Đóng và xem tiếp/i.test(label)) continue;
        hardHide(el);
        const prev = el.previousElementSibling;
        if (prev && (prev.tagName === 'IMG' || prev.querySelector?.('img'))) hardHide(prev);
        const row = el.parentElement;
        if (row?.previousElementSibling) {
          const above = row.previousElementSibling;
          if (above.querySelector?.('img, picture, video, canvas') || above.tagName === 'IMG') {
            hardHide(above);
          }
        }
      }
      document.querySelectorAll('img').forEach(img => {
        if (!visible(img)) return;
        const shell = img.closest('div, section, article');
        if (!shell?.textContent) return;
        if (!/Đóng và xem tiếp/i.test(shell.textContent)) return;
        if (!/Đóng quảng cáo|Quảng cáo/i.test(shell.textContent)) return;
        const r = img.getBoundingClientRect();
        if (r.width < 64 || r.height < 32) return;
        hardHide(img);
      });
    }

    /**
     * Walk up from real “Đóng và xem tiếp” control — most reliable anchor for the pause-ad card / backdrop.
     */
    function hidePauseAdFromContinueAncestor() {
      const clickables = document.querySelectorAll(
        'button, a, [role="button"], input[type="button"], [class*="btn"], div[onclick], span[onclick]'
      );
      for (const btn of clickables) {
        if (!visible(btn)) continue;
        const label = norm(btn.textContent);
        if (!/Đóng và xem tiếp/i.test(label)) continue;
        if (/Đóng quảng cáo/i.test(label)) continue;
        let p = btn.parentElement;
        for (let d = 0; d < 16 && p; d++) {
          if (p.querySelector?.('video')) break;
          const blob = (p.innerText || '').slice(0, 2600);
          if (!/Quảng cáo/i.test(blob)) {
            p = p.parentElement;
            continue;
          }
          const hasImg = !!p.querySelector?.('img, picture');
          const hasTrap = /Đóng quảng cáo/i.test(blob);
          if (!hasImg && !hasTrap) {
            p = p.parentElement;
            continue;
          }
          const r = p.getBoundingClientRect();
          if (r.width < 120 || r.height < 90) {
            p = p.parentElement;
            continue;
          }
          hardHide(p);
          log('Hidden pause-ad block (ancestor of “Đóng và xem tiếp”)');
          return true;
        }
      }
      return false;
    }

    /** Fallback: fixed/absolute/sticky layer with pause-ad copy (relaxed size vs old %viewport). */
    function hidePauseAdByLayerHeuristic() {
      const video = document.querySelector('video');
      if (!video || !document.body) return false;
      for (const el of document.body.querySelectorAll('div, section, article')) {
        if (!visible(el)) continue;
        if (el.id === RESUME_CHIP_ID) continue;
        if (el.querySelector?.('video')) continue;
        const text = (el.innerText || '').slice(0, 1400);
        if (!/Quảng cáo/i.test(text) || !/Đóng và xem tiếp/i.test(text)) continue;
        const r = el.getBoundingClientRect();
        if (r.width < 110 || r.height < 70) continue;
        const pos = getComputedStyle(el).position;
        if (!['fixed', 'absolute', 'sticky'].includes(pos)) continue;
        hardHide(el);
        log('Hidden pause-ad layer (position + text heuristic)');
        try {
          if (video.paused) video.play().catch(() => {});
        } catch (_) {
          /* ignore */
        }
        return true;
      }
      return false;
    }

    /** Smallest matching div with all three strings — inner card when backdrop did not match. */
    function hideSmallestPauseAdCard() {
      let best = null;
      let bestArea = Infinity;
      for (const el of document.querySelectorAll('div')) {
        if (!visible(el) || el.querySelector?.('video') || el.id === RESUME_CHIP_ID) continue;
        const t = (el.innerText || '').slice(0, 900);
        if (!/Quảng cáo/i.test(t) || !/Đóng và xem tiếp/i.test(t) || !/Đóng quảng cáo/i.test(t)) continue;
        const r = el.getBoundingClientRect();
        const area = r.width * r.height;
        if (area < 12000 || area > 4e6) continue;
        if (area < bestArea) {
          bestArea = area;
          best = el;
        }
      }
      if (best) {
        hardHide(best);
        log('Hidden smallest pause-ad card (triple-text match)');
        return true;
      }
      return false;
    }

    function tryDismissSdk() {
      const candidates = document.querySelectorAll(
        'button, a, [role="button"], input[type="button"], [class*="btn"], div[onclick], span[onclick]'
      );
      for (const el of candidates) {
        const text = norm(el.textContent);
        if (/Đóng và xem tiếp/i.test(text) && visible(el)) {
          try {
            el.click();
          } catch (_) {
            /* ignore */
          }
          log('Clicked “Đóng và xem tiếp”');
          return true;
        }
      }
      return false;
    }

    function ensureResumeChip() {
      if (document.getElementById(RESUME_CHIP_ID)) return;
      const chip = document.createElement('button');
      chip.id = RESUME_CHIP_ID;
      chip.type = 'button';
      chip.textContent = '▶ Tiếp tục';
      chip.setAttribute('aria-label', 'Tiếp tục phát');
      chip.style.cssText = [
        'position:fixed',
        'left:50%',
        'bottom:max(88px,12vh)',
        'transform:translateX(-50%)',
        'z-index:2147483646',
        'display:none',
        'pointer-events:auto',
        'padding:10px 22px',
        'border:none',
        'border-radius:10px',
        'background:rgba(22,22,28,.94)',
        'color:#fff',
        'font:14px system-ui,-apple-system,sans-serif',
        'cursor:pointer',
        'box-shadow:0 4px 20px rgba(0,0,0,.5)',
      ].join(';');
      chip.addEventListener('click', () => {
        mitigatePauseAd();
        const v = document.querySelector('video');
        if (v) v.play().catch(() => {});
        chip.style.display = 'none';
      });
      (document.documentElement || document.body).appendChild(chip);
      log('Resume chip installed');
    }

    function syncResumeChip() {
      const chip = document.getElementById(RESUME_CHIP_ID);
      if (!chip) return;
      const v = document.querySelector('video');
      chip.style.display = v && v.paused ? 'block' : 'none';
    }

    function mitigatePauseAd() {
      tryDismissSdk();
      hidePauseAdParts();
      hidePauseAdFromContinueAncestor();
      hidePauseAdByLayerHeuristic();
      hideSmallestPauseAdCard();
      syncResumeChip();
    }

    function scheduleMitigate() {
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(mitigatePauseAd, debounceMs);
    }

    function startBurst() {
      burstUntil = Date.now() + 14000;
    }

    blockDeceptiveAdCloseClicks();
    ensureResumeChip();
    mitigatePauseAd();

    document.addEventListener(
      'pause',
      e => {
        if (e.target?.tagName !== 'VIDEO') return;
        startBurst();
        mitigatePauseAd();
        scheduleMitigate();
      },
      true
    );

    document.addEventListener(
      'play',
      e => {
        if (e.target?.tagName !== 'VIDEO') return;
        burstUntil = 0;
        syncResumeChip();
      },
      true
    );

    burstTimer = window.setInterval(() => {
      if (Date.now() > burstUntil) return;
      const v = document.querySelector('video');
      if (v?.paused) mitigatePauseAd();
    }, 380);

    const root = document.documentElement || document.body;
    if (root) {
      mo = new MutationObserver(scheduleMitigate);
      mo.observe(root, { childList: true, subtree: true });
      log('Pause-ad pipeline active');
    }

    window.addEventListener(
      'pagehide',
      () => {
        clearTimeout(debounceTimer);
        debounceTimer = 0;
        clearInterval(burstTimer);
        burstTimer = 0;
        burstUntil = 0;
        mo?.disconnect();
        mo = null;
        document.getElementById(RESUME_CHIP_ID)?.remove();
      },
      { capture: true }
    );
  }

  if (PLAYER_CDN_HOST.test(location.hostname)) {
    runEmbeddedPlayerAdDismiss();
    return;
  }

  if (!/(animevietsub)\./.test(location.hostname)) return;

  // Edit src/adblock-core.js only; run `npm run build` to refresh content.js + tampermonkey.js.

  const CONFIG = {
    adCheckInterval: 300,
    verbose: true,
  };

  const log = (msg, icon = '✅') => CONFIG.verbose && console.log(`${icon} [AVS] ${msg}`);

  const AD_REDIRECT_HOST_RE =
    /(^|\.)((bom88|man88)\.(vin|com)|doubleclick\.net|googlesyndication\.com|adserver\.)$/i;
  const AD_REDIRECT_CODE_RE =
    /(createPopupAndRedirect|markPopupAsOpened|window\.open\s*\(|location\.(assign|replace)\s*\()/i;

  function isLikelyAdUrl(rawUrl) {
    if (!rawUrl || typeof rawUrl !== 'string') return false;
    const url = rawUrl.trim();
    if (!url || url === '#' || /^\/(?!\/)/.test(url)) return false;
    try {
      const resolved = new URL(url, location.href);
      const host = resolved.hostname || '';
      if (AD_REDIRECT_HOST_RE.test(host)) return true;
      return /(^|[./-])(ads?|adclick|popunder|popup)([./-]|$)/i.test(
        `${resolved.pathname}${resolved.search}`
      );
    } catch (_) {
      return false;
    }
  }

  /**
   * Page MAIN world: noop open/location + poll-noop popunder globals (see ads.js).
   * Use external script URL — strict CSP (e.g. animevietsub.io) blocks inline script injection.
   */
  function injectPageWorldPopupBlock() {
    const root = document.documentElement || document.head;
    if (!root) return;
    const extUrl =
      typeof chrome !== 'undefined' && chrome.runtime?.getURL
        ? chrome.runtime.getURL('page-world-hook.js')
        : null;
    if (extUrl) {
      const el = document.createElement('script');
      el.src = extUrl;
      el.async = false;
      el.addEventListener(
        'load',
        () => {
          try {
            el.remove();
          } catch (_) {
            /* ignore */
          }
        },
        { once: true }
      );
      el.addEventListener(
        'error',
        () => log('page-world-hook.js failed to load (check web_accessible_resources)', '⚠️'),
        { once: true }
      );
      root.appendChild(el);
      log('Page-world hook requested (extension script, CSP-safe) 🔗');
      return;
    }
    const pageCode = [
      '(function(){',
      '"use strict";',
      'function n(){return null;}',
      'try{window.open=n;var l=window.location;if(l){var oa=l.assign&&l.assign.bind(l);var or=l.replace&&l.replace.bind(l);if(oa){l.assign=function(u){if(!u||/((bom88|man88)\\.(vin|com)|doubleclick\\.net|googlesyndication\\.com|adserver\\.)/i.test(String(u))){return null;}return oa(u);};}if(or){l.replace=function(u){if(!u||/((bom88|man88)\\.(vin|com)|doubleclick\\.net|googlesyndication\\.com|adserver\\.)/i.test(String(u))){return null;}return or(u);};}}}catch(e){}',
      'try{',
      'var poll=setInterval(function(){',
      'try{',
      'if(typeof window.createPopupAndRedirect==="function"&&!window.__avsPR){window.__avsPR=1;window.createPopupAndRedirect=function(){};}',
      'if(typeof window.markPopupAsOpened==="function"&&!window.__avsPM){window.__avsPM=1;window.markPopupAsOpened=function(){};}',
      '}catch(_){}',
      '},130);',
      'setTimeout(function(){clearInterval(poll);},25e3);',
      '}catch(_){}',
      '})();',
    ].join('');
    const fallback = document.createElement('script');
    fallback.textContent = pageCode;
    root.appendChild(fallback);
    fallback.remove();
    log('Page-world hook injected (inline fallback — may be blocked by strict CSP) 🔗');
  }

  function stripGlobalOnclickIfAdTrap() {
    for (const el of [document.body, document.documentElement]) {
      const inline = el?.getAttribute?.('onclick') || '';
      if (AD_REDIRECT_CODE_RE.test(inline)) {
        el.removeAttribute('onclick');
      }
    }
  }

  function shouldBlockClickTarget(target) {
    if (!target) return false;
    const inline = target.getAttribute?.('onclick') || '';
    if (inline && AD_REDIRECT_CODE_RE.test(inline)) return true;

    const href = target.getAttribute?.('href') || '';
    if (href && /^javascript:/i.test(href) && AD_REDIRECT_CODE_RE.test(href)) return true;
    if (isLikelyAdUrl(href)) return true;

    for (const attr of ['data-href', 'data-url', 'data-target']) {
      const maybe = target.getAttribute?.(attr);
      if (isLikelyAdUrl(maybe)) return true;
    }
    return false;
  }

  function blockAdRedirectClicks() {
    document.addEventListener(
      'click',
      e => {
        const hit = e.target?.closest?.(
          'a, button, [role="button"], [onclick], [data-href], [data-url], [data-target]'
        );
        if (!hit || !shouldBlockClickTarget(hit)) return;
        e.preventDefault();
        e.stopImmediatePropagation();
        log('Blocked ad redirect click 💣');
      },
      { capture: true, passive: false }
    );
    log('Targeted popup/redirect click guard on 🚫');
  }

  function blockPopupFunctions() {
    stripGlobalOnclickIfAdTrap();
    blockAdRedirectClicks();
  }

  const adSelectors = [
    '#_preload-ads-1',
    '#_preload-ads-2',
    // Popunder bundle (see ads.js in repo) — remove tag if still in DOM before run; globals still neutralised in inject.
    'script[src*="bom88.vin"]',
    'script[src*="bom88"]',
    'script[src*="/ads.js"]',
    'script[src*="ads.js?"]',
    '#invideo_wrapper',
    'main .Ads.ads_player',
    '.Ads.ads_player',
    '.Adv.ad-center-header',
    '.header-ads-pc',
    '.header-ads-mobile',
    '.header-ads-pc a',
    '.header-ads-mobile a',
    '.pc_catfix_adv',
    '.mobile-catfish-top',
    '.mobile-catfixx',
    '.is-catfish',
    '.below-player',
    '.below-player a',
    '.below-playerm a',
    '.ad-overlay',
    '.popup-ads',
    '.sspp-modal',
    '.sspp-area',
    '.man88',
    'div[class*="popup"][class*="overlay"]',
    '.top-banner',
    '.bottom-banner',
    '.sticky-ads',
    '.floating-ads',
    '.advertisement',
    '[class*="advertisement"]',
    '[id*="advertisement"]',
    '[class*="sponsored"]',
    '[id*="sponsored"]',
    // Avoid iframe[src*="88"|"bet"|"qc"] — hex player URLs often contain those substrings and the main player iframe was removed (video flash then gone).
    'iframe[src*="doubleclick"]',
    'iframe[src*="googlesyndication"]',
    'iframe[src*="adserver"]',
    '.adsbygoogle',
    'ins.adsbygoogle',
    '#pc-catfixx a',
    '#pc-catfixx',
    '#mobile-catfish-top a',
    '#mobile-catfixx a',
    '#mobile-catfixx',
    'center a',
    '.Ads',
    '.Adv',
    '.ads',
  ];

  /** Never strip the embedded player iframe or its host box (false positives from broad selectors). */
  function mustNotRemove(el) {
    if (!el || el.nodeType !== Node.ELEMENT_NODE) return true;
    if (el.tagName === 'SCRIPT') {
      const s = el.getAttribute('src') || '';
      if (/storage\.googleapiscdn\.com/i.test(s)) return true;
      if (/\/player\//i.test(s)) return true;
    }
    if (el.tagName === 'IFRAME') {
      const src = el.getAttribute('src') || '';
      if (/storage\.googleapiscdn\.com\/player\//i.test(src)) return true;
      if (el.closest?.('#media-player, #media-player-box, #watch-block')) return true;
    }
    if (typeof el.querySelector === 'function') {
      const mainPlayer = el.querySelector?.(
        'iframe[src*="storage.googleapiscdn.com/player/"]'
      );
      if (mainPlayer) return true;
    }
    return false;
  }

  const hideAds = () => {
    let count = 0;
    for (const selector of adSelectors) {
      try {
        document.querySelectorAll(selector).forEach(el => {
          if (el?.isConnected && !mustNotRemove(el)) {
            el.remove();
            count++;
          }
        });
      } catch {
        /* invalid selector */
      }
    }
    if (count) log(`Removed ${count} ad elements 🧹`);
  };

  let domObserver = null;
  let hideAdsDebounceTimer = 0;

  function hidePreloadNode(el) {
    if (!el || el.nodeType !== Node.ELEMENT_NODE) return;
    const id = el.getAttribute('id');
    if (!id || !id.startsWith('_preload-ads')) return;
    el.style.setProperty('display', 'none', 'important');
    el.style.setProperty('visibility', 'hidden', 'important');
    el.style.setProperty('opacity', '0', 'important');
    el.innerHTML = '';
    log('Hidden #_preload-ads 🔒');
  }

  function processMutationBatch(mutations) {
    for (const m of mutations) {
      for (const n of m.addedNodes) {
        if (n.nodeType !== Node.ELEMENT_NODE) continue;
        hidePreloadNode(n);
        if (typeof n.querySelectorAll === 'function') {
          n.querySelectorAll('[id^="_preload-ads"]').forEach(hidePreloadNode);
        }
      }
    }
    clearTimeout(hideAdsDebounceTimer);
    hideAdsDebounceTimer = setTimeout(hideAds, CONFIG.adCheckInterval);
  }

  function runPreloadPassOnce() {
    for (const sel of ['#_preload-ads-1', '#_preload-ads-2']) {
      hidePreloadNode(document.querySelector(sel));
    }
  }

  function startDomObserver() {
    if (!document.body) return;
    domObserver?.disconnect();
    domObserver = new MutationObserver(processMutationBatch);
    domObserver.observe(document.body, { childList: true, subtree: true });
    log('MutationObserver (ads + preload) started 🔁');
  }

  function cleanup() {
    clearTimeout(hideAdsDebounceTimer);
    hideAdsDebounceTimer = 0;
    domObserver?.disconnect();
    domObserver = null;
  }

  function init() {
    hideAds();
    runPreloadPassOnce();
    startDomObserver();
    blockPopupFunctions();
    log('AdBlock fully initialized ✅');
  }

  injectPageWorldPopupBlock();

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init, { once: true });
  } else {
    init();
  }

  window.addEventListener('pagehide', cleanup, { capture: true });
})();
