import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

const corePath = path.join(root, 'src', 'adblock-core.js');
const headerPath = path.join(root, 'src', 'tampermonkey-header.txt');
const outContent = path.join(root, 'content.js');
const outTamper = path.join(root, 'tampermonkey.js');

const core = fs.readFileSync(corePath, 'utf8');
const header = fs.readFileSync(headerPath, 'utf8').replace(/\s+$/, '');

const banner =
  '// Generated by `npm run build` — edit src/adblock-core.js + src/tampermonkey-header.txt only.\n\n';

fs.writeFileSync(outContent, banner + core, 'utf8');
fs.writeFileSync(outTamper, `${header}\n\n${core}\n`, 'utf8');

console.log('OK: wrote content.js and tampermonkey.js from src/adblock-core.js');
